# shamelessly stolen https://github.com/chocolatey/chocolatey-cookbook/blob/master/appveyor.yml
# blog post here http://www.hurryupandwait.io/blog/run-kitchen-tests-in-travis-and-appveyor-using-the-kitchen-machine-driver

version: "master-{build}"

os: Windows Server 2012 R2
platform:
  - x64

environment:
  winrm_user: test_user
  winrm_pass: Pass@word1
  winrm_port: 5985
  KITCHEN_YAML: c:\projects\nugetclient\.kitchen.appveyor.yml
  SSL_CERT_FILE: c:\projects\nugetclient\certs.pem

  matrix:
    - ruby_version: "21"

clone_folder: c:\projects\nugetclient
clone_depth: 1
branches:
  only:
    - master

install:
  - ps: net user /add $env:winrm_user $env:winrm_pass
  - ps: net localgroup administrators $env:winrm_user /add
  - ps: $env:PATH="C:\Ruby$env:ruby_version\bin;$env:PATH"
  - ps: Write-Host $env:PATH
  - ps: ruby --version
  - ps: gem --version
  - ps: gem install bundler --quiet --no-ri --no-rdoc
  - ps: Invoke-WebRequest -Uri http://curl.haxx.se/ca/cacert.pem -OutFile c:\projects\chocolatey-cookbook\certs.pem
  - ps: bundler --version

build_script:
  - bundle install || bundle install || bundle install
  - pushd c:\projects\nugetclient\test\cookbooks\test-nugetclient\
  - bundle install || bundle install || bundle install
  - popd

test_script:
  - bundle exec rake 
  - pushd c:\projects\nugetclient\test\cookbooks\test-nugetclient\
  - bundle exec kitchen verify

